// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Agendamento")]
[Index("DataAtendimento", Name = "IX_Agendamento_Data")]
[Index("IdEmpresa", Name = "IX_Agendamento_Empresa")]
[Index("IdFuncionario", "DataAtendimento", "HoraInicio", Name = "UX_Agendamento", IsUnique = true)]
public partial class Agendamento
{
    [Key]
    public int IdAgendamento { get; set; }

    public int? IdPaciente { get; set; }

    public int? IdFuncionario { get; set; }

    public int? IdProcedimento { get; set; }

    public DateOnly? DataAtendimento { get; set; }

    public TimeOnly? HoraInicio { get; set; }

    public TimeOnly? HoraFim { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Status { get; set; }

    [Unicode(false)]
    public string Observacao { get; set; }

    public int IdEmpresa { get; set; }

    public int? IdSala { get; set; }

    [InverseProperty("IdAgendamentoNavigation")]
    public virtual ICollection<Atendimento> Atendimentos { get; set; } = new List<Atendimento>();

    [ForeignKey("IdEmpresa")]
    [InverseProperty("Agendamentos")]
    public virtual Empresa IdEmpresaNavigation { get; set; }

    [ForeignKey("IdFuncionario")]
    [InverseProperty("Agendamentos")]
    public virtual Funcionario IdFuncionarioNavigation { get; set; }

    [ForeignKey("IdPaciente")]
    [InverseProperty("Agendamentos")]
    public virtual Paciente IdPacienteNavigation { get; set; }

    [ForeignKey("IdProcedimento")]
    [InverseProperty("Agendamentos")]
    public virtual Procedimento IdProcedimentoNavigation { get; set; }
}