// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("AnexoPaciente")]
public partial class AnexoPaciente
{
    [Key]
    public int IdAnexo { get; set; }

    public int? IdPaciente { get; set; }

    [StringLength(300)]
    [Unicode(false)]
    public string NomeArquivo { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string CaminhoArquivo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataUpload { get; set; }

    public int IdEmpresa { get; set; }

    [ForeignKey("IdEmpresa")]
    [InverseProperty("AnexoPacientes")]
    public virtual Empresa IdEmpresaNavigation { get; set; }

    [ForeignKey("IdPaciente")]
    [InverseProperty("AnexoPacientes")]
    public virtual Paciente IdPacienteNavigation { get; set; }
}