// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("AssinaturaDigital")]
public partial class AssinaturaDigital
{
    [Key]
    public int IdAssinatura { get; set; }

    public int? IdProntuario { get; set; }

    [Unicode(false)]
    public string HashDocumento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataAssinatura { get; set; }
}