// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Atendimento")]
[Index("DataRealizacao", Name = "IX_Atendimento_Data")]
[Index("IdEmpresa", Name = "IX_Atendimento_Empresa")]
public partial class Atendimento
{
    [Key]
    public int IdAtendimento { get; set; }

    public int? IdAgendamento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataRealizacao { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ValorCobrado { get; set; }

    public bool? Faturado { get; set; }

    public int IdEmpresa { get; set; }

    [InverseProperty("IdAtendimentoNavigation")]
    public virtual ICollection<ContaReceber> ContaRecebers { get; set; } = new List<ContaReceber>();

    [ForeignKey("IdAgendamento")]
    [InverseProperty("Atendimentos")]
    public virtual Agendamento IdAgendamentoNavigation { get; set; }

    [ForeignKey("IdEmpresa")]
    [InverseProperty("Atendimentos")]
    public virtual Empresa IdEmpresaNavigation { get; set; }
}