// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

public partial class Auditorium
{
    [Key]
    public int IdAuditoria { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Tabela { get; set; }

    public int? RegistroId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Operacao { get; set; }

    [Unicode(false)]
    public string ValorAnterior { get; set; }

    [Unicode(false)]
    public string ValorNovo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataOperacao { get; set; }

    public int? IdUsuario { get; set; }
}