// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Caixa")]
public partial class Caixa
{
    [Key]
    public int IdCaixa { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataMovimento { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Valor { get; set; }

    public int IdEmpresa { get; set; }

    [ForeignKey("IdEmpresa")]
    [InverseProperty("Caixas")]
    public virtual Empresa IdEmpresaNavigation { get; set; }
}