// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("ConsentimentoLGPD")]
public partial class ConsentimentoLGPD
{
    [Key]
    public int IdConsentimento { get; set; }

    public int IdPaciente { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataConsentimento { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string VersaoTermo { get; set; }

    public bool Aceitou { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string IP { get; set; }

    [ForeignKey("IdPaciente")]
    [InverseProperty("ConsentimentoLGPDs")]
    public virtual Paciente IdPacienteNavigation { get; set; }
}