// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("ContaPagar")]
public partial class ContaPagar
{
    [Key]
    public int IdContaPagar { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Valor { get; set; }

    public DateOnly? DataVencimento { get; set; }

    public DateOnly? DataPagamento { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Situacao { get; set; }

    public int IdEmpresa { get; set; }

    [ForeignKey("IdEmpresa")]
    [InverseProperty("ContaPagars")]
    public virtual Empresa IdEmpresaNavigation { get; set; }
}