// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("ContaReceber")]
[Index("IdEmpresa", Name = "IX_ContaReceber_Empresa")]
public partial class ContaReceber
{
    [Key]
    public int IdContaReceber { get; set; }

    public int? IdAtendimento { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Valor { get; set; }

    public DateOnly? DataVencimento { get; set; }

    public DateOnly? DataPagamento { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Situacao { get; set; }

    public int IdEmpresa { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FormaPagamento { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Desconto { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Juros { get; set; }

    [ForeignKey("IdAtendimento")]
    [InverseProperty("ContaRecebers")]
    public virtual Atendimento IdAtendimentoNavigation { get; set; }

    [ForeignKey("IdEmpresa")]
    [InverseProperty("ContaRecebers")]
    public virtual Empresa IdEmpresaNavigation { get; set; }
}