// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Cooperativa")]
public partial class Cooperativa
{
    [Key]
    public int IdCooperativa { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string NomeCooperativa { get; set; }

    [StringLength(18)]
    [Unicode(false)]
    public string CNPJ { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Contato { get; set; }

    public bool? Ativa { get; set; }

    public int IdEmpresa { get; set; }

    [ForeignKey("IdEmpresa")]
    [InverseProperty("Cooperativas")]
    public virtual Empresa IdEmpresaNavigation { get; set; }

    [InverseProperty("IdCooperativaNavigation")]
    public virtual ICollection<PacienteCooperativa> PacienteCooperativas { get; set; } = new List<PacienteCooperativa>();

    [InverseProperty("IdCooperativaNavigation")]
    public virtual ICollection<ProcedimentoCooperativa> ProcedimentoCooperativas { get; set; } = new List<ProcedimentoCooperativa>();
}