// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

public partial class DATAFISIOContext : DbContext
{
    public DATAFISIOContext()
    {
    }

    public DATAFISIOContext(DbContextOptions<DATAFISIOContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Agendamento> Agendamentos { get; set; }

    public virtual DbSet<AnexoPaciente> AnexoPacientes { get; set; }

    public virtual DbSet<AssinaturaDigital> AssinaturaDigitals { get; set; }

    public virtual DbSet<Atendimento> Atendimentos { get; set; }

    public virtual DbSet<Auditorium> Auditoria { get; set; }

    public virtual DbSet<Caixa> Caixas { get; set; }

    public virtual DbSet<ConsentimentoLGPD> ConsentimentoLGPDs { get; set; }

    public virtual DbSet<ContaPagar> ContaPagars { get; set; }

    public virtual DbSet<ContaReceber> ContaRecebers { get; set; }

    public virtual DbSet<Cooperativa> Cooperativas { get; set; }

    public virtual DbSet<Empresa> Empresas { get; set; }

    public virtual DbSet<Equipamento> Equipamentos { get; set; }

    public virtual DbSet<EvolucaoClinica> EvolucaoClinicas { get; set; }

    public virtual DbSet<Funcionario> Funcionarios { get; set; }

    public virtual DbSet<Notificacao> Notificacaos { get; set; }

    public virtual DbSet<Paciente> Pacientes { get; set; }

    public virtual DbSet<PacienteCooperativa> PacienteCooperativas { get; set; }

    public virtual DbSet<Perfil> Perfils { get; set; }

    public virtual DbSet<PlanoTratamento> PlanoTratamentos { get; set; }

    public virtual DbSet<Procedimento> Procedimentos { get; set; }

    public virtual DbSet<ProcedimentoCooperativa> ProcedimentoCooperativas { get; set; }

    public virtual DbSet<Prontuario> Prontuarios { get; set; }

    public virtual DbSet<RecuperacaoSenha> RecuperacaoSenhas { get; set; }

    public virtual DbSet<Sala> Salas { get; set; }

    public virtual DbSet<SessaoUsuario> SessaoUsuarios { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<UsuarioPerfil> UsuarioPerfils { get; set; }

    public virtual DbSet<VW_FaturamentoMensal> VW_FaturamentoMensals { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=MANIHOISAAC;Initial Catalog=DATAFISIO;User ID=Carlos.Oliveira;Password=123;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Agendamento>(entity =>
        {
            entity.HasKey(e => e.IdAgendamento).HasName("PK__Agendame__DC0823C918951522");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.Agendamentos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Agendamento_Empresa");

            entity.HasOne(d => d.IdFuncionarioNavigation).WithMany(p => p.Agendamentos).HasConstraintName("FK__Agendamen__IdFun__5812160E");

            entity.HasOne(d => d.IdPacienteNavigation).WithMany(p => p.Agendamentos).HasConstraintName("FK__Agendamen__IdPac__571DF1D5");

            entity.HasOne(d => d.IdProcedimentoNavigation).WithMany(p => p.Agendamentos).HasConstraintName("FK__Agendamen__IdPro__59063A47");
        });

        modelBuilder.Entity<AnexoPaciente>(entity =>
        {
            entity.HasKey(e => e.IdAnexo).HasName("PK__AnexoPac__8C1FE271DB7FEDE0");

            entity.Property(e => e.DataUpload).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.AnexoPacientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AnexoPaciente_Empresa");

            entity.HasOne(d => d.IdPacienteNavigation).WithMany(p => p.AnexoPacientes).HasConstraintName("FK__AnexoPaci__IdPac__6E01572D");
        });

        modelBuilder.Entity<AssinaturaDigital>(entity =>
        {
            entity.HasKey(e => e.IdAssinatura).HasName("PK__Assinatu__8017D889A86C2279");
        });

        modelBuilder.Entity<Atendimento>(entity =>
        {
            entity.HasKey(e => e.IdAtendimento).HasName("PK__Atendime__84DAE47F3EF48FFD");

            entity.Property(e => e.Faturado).HasDefaultValue(false);

            entity.HasOne(d => d.IdAgendamentoNavigation).WithMany(p => p.Atendimentos).HasConstraintName("FK__Atendimen__IdAge__6383C8BA");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.Atendimentos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Atendimento_Empresa");
        });

        modelBuilder.Entity<Auditorium>(entity =>
        {
            entity.HasKey(e => e.IdAuditoria).HasName("PK__Auditori__7FD13FA0CF422F31");

            entity.Property(e => e.DataOperacao).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Caixa>(entity =>
        {
            entity.HasKey(e => e.IdCaixa).HasName("PK__Caixa__6548B857160E4443");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.Caixas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Caixa_Empresa");
        });

        modelBuilder.Entity<ConsentimentoLGPD>(entity =>
        {
            entity.HasKey(e => e.IdConsentimento).HasName("PK__Consenti__BCE29BEA950201D8");

            entity.HasOne(d => d.IdPacienteNavigation).WithMany(p => p.ConsentimentoLGPDs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Consentim__IdPac__08B54D69");
        });

        modelBuilder.Entity<ContaPagar>(entity =>
        {
            entity.HasKey(e => e.IdContaPagar).HasName("PK__ContaPag__3360276C7F9FAC9D");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.ContaPagars)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContaPagar_Empresa");
        });

        modelBuilder.Entity<ContaReceber>(entity =>
        {
            entity.HasKey(e => e.IdContaReceber).HasName("PK__ContaRec__D61DBA8D4969FA2C");

            entity.HasOne(d => d.IdAtendimentoNavigation).WithMany(p => p.ContaRecebers).HasConstraintName("FK__ContaRece__IdAte__66603565");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.ContaRecebers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContaReceber_Empresa");
        });

        modelBuilder.Entity<Cooperativa>(entity =>
        {
            entity.HasKey(e => e.IdCooperativa).HasName("PK__Cooperat__44C46A1004687EC4");

            entity.Property(e => e.Ativa).HasDefaultValue(true);

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.Cooperativas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cooperativa_Empresa");
        });

        modelBuilder.Entity<Empresa>(entity =>
        {
            entity.HasKey(e => e.IdEmpresa).HasName("PK__Empresa__5EF4033EDC865E9D");

            entity.Property(e => e.DataCadastro).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Estado).IsFixedLength();
        });

        modelBuilder.Entity<Equipamento>(entity =>
        {
            entity.HasKey(e => e.IdEquipamento).HasName("PK__Equipame__E309D87FFA4305C2");

            entity.Property(e => e.Ativo).HasDefaultValue(true);
        });

        modelBuilder.Entity<EvolucaoClinica>(entity =>
        {
            entity.HasKey(e => e.IdEvolucao).HasName("PK__Evolucao__D276D8BF7C3811D4");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.EvolucaoClinicas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EvolucaoClinica_Empresa");

            entity.HasOne(d => d.IdProntuarioNavigation).WithMany(p => p.EvolucaoClinicas).HasConstraintName("FK__EvolucaoC__IdPro__5FB337D6");
        });

        modelBuilder.Entity<Funcionario>(entity =>
        {
            entity.HasKey(e => e.IdFuncionario).HasName("PK__Funciona__35CB052ADD0A0300");

            entity.Property(e => e.Ativo).HasDefaultValue(true);

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.Funcionarios)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Funcionario_Empresa");
        });

        modelBuilder.Entity<Notificacao>(entity =>
        {
            entity.HasKey(e => e.IdNotificacao).HasName("PK__Notifica__046D3872AA80542F");

            entity.Property(e => e.DataEnvio).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Lida).HasDefaultValue(false);
        });

        modelBuilder.Entity<Paciente>(entity =>
        {
            entity.HasKey(e => e.IdPaciente).HasName("PK__Paciente__C93DB49BDA2C6B7B");

            entity.Property(e => e.Ativo).HasDefaultValue(true);
            entity.Property(e => e.DataCadastro).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Estado).IsFixedLength();
            entity.Property(e => e.Sexo).IsFixedLength();

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.Pacientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Paciente_Empresa");
        });

        modelBuilder.Entity<PacienteCooperativa>(entity =>
        {
            entity.HasKey(e => e.IdPacienteCooperativa).HasName("PK__Paciente__B70EF56E1746236F");

            entity.HasOne(d => d.IdCooperativaNavigation).WithMany(p => p.PacienteCooperativas).HasConstraintName("FK__PacienteC__IdCoo__47DBAE45");

            entity.HasOne(d => d.IdPacienteNavigation).WithMany(p => p.PacienteCooperativas).HasConstraintName("FK__PacienteC__IdPac__46E78A0C");
        });

        modelBuilder.Entity<Perfil>(entity =>
        {
            entity.HasKey(e => e.IdPerfil).HasName("PK__Perfil__C7BD5CC1CF6226DE");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.Perfils).HasConstraintName("FK_Perfil_Empresa");
        });

        modelBuilder.Entity<PlanoTratamento>(entity =>
        {
            entity.HasKey(e => e.IdPlanoTratamento).HasName("PK__PlanoTra__7618E82FFBB51BCB");

            entity.Property(e => e.SessoesRealizadas).HasDefaultValue(0);

            entity.HasOne(d => d.IdPacienteNavigation).WithMany(p => p.PlanoTratamentos).HasConstraintName("FK__PlanoTrat__IdPac__10566F31");

            entity.HasOne(d => d.IdProcedimentoNavigation).WithMany(p => p.PlanoTratamentos).HasConstraintName("FK__PlanoTrat__IdPro__114A936A");
        });

        modelBuilder.Entity<Procedimento>(entity =>
        {
            entity.HasKey(e => e.IdProcedimento).HasName("PK__Procedim__8DD91F10CD848E4F");

            entity.Property(e => e.Ativo).HasDefaultValue(true);

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.Procedimentos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Procedimento_Empresa");
        });

        modelBuilder.Entity<ProcedimentoCooperativa>(entity =>
        {
            entity.HasKey(e => e.IdProcedimentoCooperativa).HasName("PK__Procedim__41643D6A6617CDAF");

            entity.HasOne(d => d.IdCooperativaNavigation).WithMany(p => p.ProcedimentoCooperativas).HasConstraintName("FK__Procedime__IdCoo__412EB0B6");

            entity.HasOne(d => d.IdProcedimentoNavigation).WithMany(p => p.ProcedimentoCooperativas).HasConstraintName("FK__Procedime__IdPro__403A8C7D");
        });

        modelBuilder.Entity<Prontuario>(entity =>
        {
            entity.HasKey(e => e.IdProntuario).HasName("PK__Prontuar__3AB81E6617EABA04");

            entity.Property(e => e.DataAbertura).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.Prontuarios)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Prontuario_Empresa");

            entity.HasOne(d => d.IdPacienteNavigation).WithMany(p => p.Prontuarios).HasConstraintName("FK__Prontuari__IdPac__5CD6CB2B");
        });

        modelBuilder.Entity<RecuperacaoSenha>(entity =>
        {
            entity.HasKey(e => e.IdRecuperacao).HasName("PK__Recupera__0BD5D63F586296AC");

            entity.Property(e => e.Utilizado).HasDefaultValue(false);

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.RecuperacaoSenhas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Recuperac__IdUsu__2739D489");
        });

        modelBuilder.Entity<Sala>(entity =>
        {
            entity.HasKey(e => e.IdSala).HasName("PK__Sala__A04F9B3B072EBFCD");

            entity.Property(e => e.Ativa).HasDefaultValue(true);
        });

        modelBuilder.Entity<SessaoUsuario>(entity =>
        {
            entity.HasKey(e => e.IdSessao).HasName("PK__SessaoUs__4641A64D79C6D7ED");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.SessaoUsuarios)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SessaoUsu__IdUsu__2A164134");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__Usuario__5B65BF97AA3142F9");

            entity.Property(e => e.Ativo).HasDefaultValue(true);
            entity.Property(e => e.DataCriacao).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.Usuarios)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_Empresa");

            entity.HasOne(d => d.IdFuncionarioNavigation).WithMany(p => p.Usuarios).HasConstraintName("FK__Usuario__IdFunci__4E88ABD4");
        });

        modelBuilder.Entity<UsuarioPerfil>(entity =>
        {
            entity.HasKey(e => e.IdUsuarioPerfil).HasName("PK__UsuarioP__96C517D5DDDDDB23");

            entity.HasOne(d => d.IdPerfilNavigation).WithMany(p => p.UsuarioPerfils).HasConstraintName("FK__UsuarioPe__IdPer__5441852A");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.UsuarioPerfils).HasConstraintName("FK__UsuarioPe__IdUsu__534D60F1");
        });

        modelBuilder.Entity<VW_FaturamentoMensal>(entity =>
        {
            entity.ToView("VW_FaturamentoMensal");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}