// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Empresa")]
[Index("CNPJ", Name = "UQ_Empresa_CNPJ", IsUnique = true)]
public partial class Empresa
{
    [Key]
    public int IdEmpresa { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string RazaoSocial { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string NomeFantasia { get; set; }

    [StringLength(18)]
    [Unicode(false)]
    public string CNPJ { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string InscricaoEstadual { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Site { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string CEP { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Endereco { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Numero { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Complemento { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Bairro { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string Estado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<Agendamento> Agendamentos { get; set; } = new List<Agendamento>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<AnexoPaciente> AnexoPacientes { get; set; } = new List<AnexoPaciente>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<Atendimento> Atendimentos { get; set; } = new List<Atendimento>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<Caixa> Caixas { get; set; } = new List<Caixa>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<ContaPagar> ContaPagars { get; set; } = new List<ContaPagar>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<ContaReceber> ContaRecebers { get; set; } = new List<ContaReceber>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<Cooperativa> Cooperativas { get; set; } = new List<Cooperativa>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<EvolucaoClinica> EvolucaoClinicas { get; set; } = new List<EvolucaoClinica>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<Funcionario> Funcionarios { get; set; } = new List<Funcionario>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<Paciente> Pacientes { get; set; } = new List<Paciente>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<Perfil> Perfils { get; set; } = new List<Perfil>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<Procedimento> Procedimentos { get; set; } = new List<Procedimento>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<Prontuario> Prontuarios { get; set; } = new List<Prontuario>();

    [InverseProperty("IdEmpresaNavigation")]
    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}