// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Equipamento")]
public partial class Equipamento
{
    [Key]
    public int IdEquipamento { get; set; }

    public int? IdEmpresa { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string NomeEquipamento { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Patrimonio { get; set; }

    public DateOnly? DataAquisicao { get; set; }

    public bool? Ativo { get; set; }
}