// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("EvolucaoClinica")]
public partial class EvolucaoClinica
{
    [Key]
    public int IdEvolucao { get; set; }

    public int? IdProntuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataEvolucao { get; set; }

    [Unicode(false)]
    public string Queixa { get; set; }

    [Unicode(false)]
    public string Diagnostico { get; set; }

    [Unicode(false)]
    public string TratamentoRealizado { get; set; }

    [Unicode(false)]
    public string Observacoes { get; set; }

    public int IdEmpresa { get; set; }

    [ForeignKey("IdEmpresa")]
    [InverseProperty("EvolucaoClinicas")]
    public virtual Empresa IdEmpresaNavigation { get; set; }

    [ForeignKey("IdProntuario")]
    [InverseProperty("EvolucaoClinicas")]
    public virtual Prontuario IdProntuarioNavigation { get; set; }
}