// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Funcionario")]
[Index("CPF", Name = "IX_Funcionario_CPF")]
[Index("IdEmpresa", Name = "IX_Funcionario_Empresa")]
[Index("CPF", Name = "UQ_Funcionario_CPF", IsUnique = true)]
public partial class Funcionario
{
    [Key]
    public int IdFuncionario { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(14)]
    [Unicode(false)]
    public string CPF { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Cargo { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Conselho { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string NumeroRegistro { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Salario { get; set; }

    public bool? Ativo { get; set; }

    public int IdEmpresa { get; set; }

    [InverseProperty("IdFuncionarioNavigation")]
    public virtual ICollection<Agendamento> Agendamentos { get; set; } = new List<Agendamento>();

    [ForeignKey("IdEmpresa")]
    [InverseProperty("Funcionarios")]
    public virtual Empresa IdEmpresaNavigation { get; set; }

    [InverseProperty("IdFuncionarioNavigation")]
    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}