// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Notificacao")]
public partial class Notificacao
{
    [Key]
    public int IdNotificacao { get; set; }

    public int? IdUsuario { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Titulo { get; set; }

    [Unicode(false)]
    public string Mensagem { get; set; }

    public bool? Lida { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataEnvio { get; set; }
}