// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("PacienteCooperativa")]
public partial class PacienteCooperativa
{
    [Key]
    public int IdPacienteCooperativa { get; set; }

    public int? IdPaciente { get; set; }

    public int? IdCooperativa { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string NumeroCarteirinha { get; set; }

    public DateOnly? Validade { get; set; }

    [ForeignKey("IdCooperativa")]
    [InverseProperty("PacienteCooperativas")]
    public virtual Cooperativa IdCooperativaNavigation { get; set; }

    [ForeignKey("IdPaciente")]
    [InverseProperty("PacienteCooperativas")]
    public virtual Paciente IdPacienteNavigation { get; set; }
}