// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Paciente")]
[Index("CPF", Name = "IX_Paciente_CPF")]
[Index("IdEmpresa", Name = "IX_Paciente_Empresa")]
[Index("CPF", Name = "UQ_Paciente_CPF", IsUnique = true)]
public partial class Paciente
{
    [Key]
    public int IdPaciente { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(14)]
    [Unicode(false)]
    public string CPF { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string RG { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Sexo { get; set; }

    public DateOnly? DataNascimento { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Celular { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string CEP { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Endereco { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Numero { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Complemento { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Bairro { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string Estado { get; set; }

    [Unicode(false)]
    public string Observacoes { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    public int IdEmpresa { get; set; }

    public bool Ativo { get; set; }

    [InverseProperty("IdPacienteNavigation")]
    public virtual ICollection<Agendamento> Agendamentos { get; set; } = new List<Agendamento>();

    [InverseProperty("IdPacienteNavigation")]
    public virtual ICollection<AnexoPaciente> AnexoPacientes { get; set; } = new List<AnexoPaciente>();

    [InverseProperty("IdPacienteNavigation")]
    public virtual ICollection<ConsentimentoLGPD> ConsentimentoLGPDs { get; set; } = new List<ConsentimentoLGPD>();

    [ForeignKey("IdEmpresa")]
    [InverseProperty("Pacientes")]
    public virtual Empresa IdEmpresaNavigation { get; set; }

    [InverseProperty("IdPacienteNavigation")]
    public virtual ICollection<PacienteCooperativa> PacienteCooperativas { get; set; } = new List<PacienteCooperativa>();

    [InverseProperty("IdPacienteNavigation")]
    public virtual ICollection<PlanoTratamento> PlanoTratamentos { get; set; } = new List<PlanoTratamento>();

    [InverseProperty("IdPacienteNavigation")]
    public virtual ICollection<Prontuario> Prontuarios { get; set; } = new List<Prontuario>();
}