// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Perfil")]
public partial class Perfil
{
    [Key]
    public int IdPerfil { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string NomePerfil { get; set; }

    public int? IdEmpresa { get; set; }

    [ForeignKey("IdEmpresa")]
    [InverseProperty("Perfils")]
    public virtual Empresa IdEmpresaNavigation { get; set; }

    [InverseProperty("IdPerfilNavigation")]
    public virtual ICollection<UsuarioPerfil> UsuarioPerfils { get; set; } = new List<UsuarioPerfil>();
}