// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("PlanoTratamento")]
public partial class PlanoTratamento
{
    [Key]
    public int IdPlanoTratamento { get; set; }

    public int? IdPaciente { get; set; }

    public int? IdProcedimento { get; set; }

    public int? QuantidadeSessoes { get; set; }

    public int? SessoesRealizadas { get; set; }

    public DateOnly? DataInicio { get; set; }

    public DateOnly? DataFim { get; set; }

    [ForeignKey("IdPaciente")]
    [InverseProperty("PlanoTratamentos")]
    public virtual Paciente IdPacienteNavigation { get; set; }

    [ForeignKey("IdProcedimento")]
    [InverseProperty("PlanoTratamentos")]
    public virtual Procedimento IdProcedimentoNavigation { get; set; }
}