// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Procedimento")]
public partial class Procedimento
{
    [Key]
    public int IdProcedimento { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CodigoProcedimento { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string NomeProcedimento { get; set; }

    public int? DuracaoMinutos { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ValorParticular { get; set; }

    public bool? Ativo { get; set; }

    public int IdEmpresa { get; set; }

    [InverseProperty("IdProcedimentoNavigation")]
    public virtual ICollection<Agendamento> Agendamentos { get; set; } = new List<Agendamento>();

    [ForeignKey("IdEmpresa")]
    [InverseProperty("Procedimentos")]
    public virtual Empresa IdEmpresaNavigation { get; set; }

    [InverseProperty("IdProcedimentoNavigation")]
    public virtual ICollection<PlanoTratamento> PlanoTratamentos { get; set; } = new List<PlanoTratamento>();

    [InverseProperty("IdProcedimentoNavigation")]
    public virtual ICollection<ProcedimentoCooperativa> ProcedimentoCooperativas { get; set; } = new List<ProcedimentoCooperativa>();
}