// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("ProcedimentoCooperativa")]
public partial class ProcedimentoCooperativa
{
    [Key]
    public int IdProcedimentoCooperativa { get; set; }

    public int? IdProcedimento { get; set; }

    public int? IdCooperativa { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Valor { get; set; }

    [ForeignKey("IdCooperativa")]
    [InverseProperty("ProcedimentoCooperativas")]
    public virtual Cooperativa IdCooperativaNavigation { get; set; }

    [ForeignKey("IdProcedimento")]
    [InverseProperty("ProcedimentoCooperativas")]
    public virtual Procedimento IdProcedimentoNavigation { get; set; }
}