// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Prontuario")]
public partial class Prontuario
{
    [Key]
    public int IdProntuario { get; set; }

    public int? IdPaciente { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataAbertura { get; set; }

    public int IdEmpresa { get; set; }

    [InverseProperty("IdProntuarioNavigation")]
    public virtual ICollection<EvolucaoClinica> EvolucaoClinicas { get; set; } = new List<EvolucaoClinica>();

    [ForeignKey("IdEmpresa")]
    [InverseProperty("Prontuarios")]
    public virtual Empresa IdEmpresaNavigation { get; set; }

    [ForeignKey("IdPaciente")]
    [InverseProperty("Prontuarios")]
    public virtual Paciente IdPacienteNavigation { get; set; }
}