// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("RecuperacaoSenha")]
public partial class RecuperacaoSenha
{
    [Key]
    public int IdRecuperacao { get; set; }

    public int IdUsuario { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataExpiracao { get; set; }

    public bool? Utilizado { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("RecuperacaoSenhas")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}