// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Sala")]
public partial class Sala
{
    [Key]
    public int IdSala { get; set; }

    public int? IdEmpresa { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string NomeSala { get; set; }

    public bool? Ativa { get; set; }
}