// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("SessaoUsuario")]
public partial class SessaoUsuario
{
    [Key]
    public int IdSessao { get; set; }

    public int IdUsuario { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataLogin { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataExpiracao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string IP { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Navegador { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("SessaoUsuarios")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}