// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("UsuarioPerfil")]
public partial class UsuarioPerfil
{
    [Key]
    public int IdUsuarioPerfil { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdPerfil { get; set; }

    [ForeignKey("IdPerfil")]
    [InverseProperty("UsuarioPerfils")]
    public virtual Perfil IdPerfilNavigation { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("UsuarioPerfils")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}