// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Table("Usuario")]
[Index("Email", Name = "IX_Usuario_Email")]
[Index("IdEmpresa", Name = "IX_Usuario_Empresa")]
[Index("Login", Name = "UX_Usuario_Login", IsUnique = true)]
public partial class Usuario
{
    [Key]
    public int IdUsuario { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Login { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string SenhaHash { get; set; }

    public int? IdFuncionario { get; set; }

    public bool? Ativo { get; set; }

    public int IdEmpresa { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UltimoLogin { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataCriacao { get; set; }

    public int TentativasLogin { get; set; }

    public bool Bloqueado { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataUltimaTrocaSenha { get; set; }

    public bool ExigirTrocaSenha { get; set; }

    [ForeignKey("IdEmpresa")]
    [InverseProperty("Usuarios")]
    public virtual Empresa IdEmpresaNavigation { get; set; }

    [ForeignKey("IdFuncionario")]
    [InverseProperty("Usuarios")]
    public virtual Funcionario IdFuncionarioNavigation { get; set; }

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<RecuperacaoSenha> RecuperacaoSenhas { get; set; } = new List<RecuperacaoSenha>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<SessaoUsuario> SessaoUsuarios { get; set; } = new List<SessaoUsuario>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<UsuarioPerfil> UsuarioPerfils { get; set; } = new List<UsuarioPerfil>();
}