// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SOFTFISIO.DATA.Models;

[Keyless]
public partial class VW_FaturamentoMensal
{
    public int? Ano { get; set; }

    public int? Mes { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal? Total { get; set; }
}